image: node:6.4
before_script:
  - npm config set spin false
  - npm install -g ember-cli
  - npm install -g phantomjs-prebuilt
  - npm install
stages:
  - test
  - deploy

test:
  stage: test
  environment: production
  script:
    - ember test

staging:
  stage: deploy
  environment: staging
  script:
    - ember deploy staging
  only:
    - master

production:
  stage: deploy
  environment: production
  script:
    - ember deploy production
  when: manual
  only:
    - master
